# Generated by Django 5.1.15 on 2026-03-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=100)),
                ('risk_level', models.CharField(max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_logs', to='academics.student')),
            ],
        ),
        migrations.CreateModel(
            name='CampusPulseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_score', models.FloatField()),
                ('attendance_component', models.FloatField()),
                ('performance_component', models.FloatField()),
                ('finance_component', models.FloatField(default=75.0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_snapshots', to='campus.school')),
            ],
        ),
    ]
