# Generated by Django 5.1.15 on 2026-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('primary_color', models.CharField(default='#22c55e', max_length=20)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=20)),
                ('attendance_threshold', models.PositiveSmallIntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
